const FETCH_SUBSCRIPTIONS_REQUEST = "fabloch/subscribe/FETCH_SUBSCRIPTIONS_REQUEST"
const FETCH_SUBSCRIPTIONS_FAILURE = "fabloch/subscribe/FETCH_SUBSCRIPTIONS_FAILURE"
const FETCH_SUBSCRIPTIONS_SUCCESS = "fabloch/subscribe/FETCH_SUBSCRIPTIONS_SUCCESS"

export default {
  FETCH_SUBSCRIPTIONS_REQUEST,
  FETCH_SUBSCRIPTIONS_FAILURE,
  FETCH_SUBSCRIPTIONS_SUCCESS,
}
