const FETCH_SUBSCRIPTIONS_REQUEST = "fabloch/subscribe/FETCH_SUBSCRIPTIONS_REQUEST"
const FETCH_SUBSCRIPTIONS_FAILURE = "fabloch/subscribe/FETCH_SUBSCRIPTIONS_FAILURE"
const FETCH_SUBSCRIPTIONS_SUCCESS = "fabloch/subscribe/FETCH_SUBSCRIPTIONS_SUCCESS"

const SELECT_PLAN = "fabloch/subscribe/SELECT_PLAN"
const SELECT_PAYMENT_METHOD = "fabloch/subscribe/SELECT_PAYMENT_METHOD"

export default {
  FETCH_SUBSCRIPTIONS_REQUEST,
  FETCH_SUBSCRIPTIONS_FAILURE,
  FETCH_SUBSCRIPTIONS_SUCCESS,
  SELECT_PLAN,
  SELECT_PAYMENT_METHOD,
}
