export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'

export const EMAIL_SIGNUP_REQUEST = 'EMAIL_SIGNUP_REQUEST'
export const EMAIL_SIGNUP_SUCCESS = 'EMAIL_SIGNUP_SUCCESS'
export const EMAIL_SIGNUP_FAILURE = 'EMAIL_SIGNUP_FAILURE'
export const BACKEND_FAILURE = 'BACKEND_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
