const LOGIN_REQUEST = "fabloch/auth/LOGIN_REQUEST"
const LOGIN_SUCCESS = "fabloch/auth/LOGIN_SUCCESS"
const LOGIN_FAILURE = "fabloch/auth/LOGIN_FAILURE"
const SET_CURRENT_USER = "fabloch/auth/SET_CURRENT_USER"
const REMOVE_CURRENT_USER = "fabloch/auth/REMOVE_CURRENT_USER"
const LOGOUT = "fabloch/auth/LOGOUT"

export default {
  SET_CURRENT_USER,
  REMOVE_CURRENT_USER,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,
}
